baseurl: "https://www.thereserveforce.com/"
title: "The Reserve Force"
theme: thereserveforce-2019

googleAnalytics: "UA-156661141-1"

enableEmoji: true

params:
  description: "Online resources for U.S. military reservists. We got your back."
  mailchimpURL: "//TheReserveForce.us19.list-manage.com/subscribe/post?u=7d0785042c911451e8e716e3b&amp;id=d42254f9f5"

markup:
  goldmark:
    renderer:
      unsafe: true

menu:
  main:
    - identifier: branches
      name: "Branches"
      weight: -1
    - parent: branches
      name: "All Branches"
      url: "/all/"
      weight: 5
    - parent: branches
      pre: '<span class="fas fa-anchor"></span>'
      name: "Navy"
      url: "/navy/"
      weight: 10
    - parent: branches
      pre: '<span class="fas fa-chevron-circle-up"></span>'
      name: "Army"
      url: "/army/"
      weight: 15
    - parent: branches
      pre: '<span class="fas fa-chevron-circle-down"></span>'
      name: "Marine Corps"
      url: "/marine-corps/"
      weight: 16
    - name: "About"
      url: "/about/"
      weight: 20
    - name: "Blog"
      url: "/blog/"
      weight: 25
    - name: "Contact Us"
      url: "/contact/"
      weight: 30
  all:
    - name: "TRF"
      url: "/all/"
      weight: -1
    - name: "Benefits"
      url: "/all/reserve-benefits/"
      weight: 5
    - name: "Pay Chart"
      url: "/all/pay-chart/"
      weight: 10
    - name: "IT Assistance"
      url: "/all/it-assistance/"
      weight: 15 
  navy:
    - name: "USN"
      url: "/navy/"
      weight: -1
    - name: "NOSCs"
      url: "/navy/nosc/"
      weight: 5
    - name: "Important Links"
      url: "/navy/important-links/"
      weight: 10
    - name: "Glossary"
      url: "/navy/glossary/"
      weight: 15
    - name: "News"
      url: "/navy/news/"
      weight: 20
    - name: "Calendar"
      url: "/navy/calendar/"
      weight: 25
  blog:
    - name: "Blog"
      url: "/blog/"
      weight: -1
    - name: "Latest Posts"
      url: "/blog/"
      weight: 5
    - name: "Submit Ideas"
      url: "/blog/submit-ideas"
      weight: 15
